---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: password-generator-ingress
  namespace: netbela
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - password.netbela.com
  rules:
    - host: password.netbela.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: password-generator
                port:
                  number: 80