---
apiVersion: v1
kind: Service
metadata:
  name: password-generator
  namespace: netbela
spec:
  selector:
    app: password-generator
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP